/**
 * Create Task form — pick project + workflow, enter title + description.
 *
 * Task ID is auto-generated by the store based on the project's prefix and
 * a fixed workflow letter (e.g. DA-017F). The optional workflow picker
 * sources from `library/_index.json` (kind:"workflow"); when one's
 * selected, on submit we write a `RUN_CONFIG.json` sidecar with the
 * chosen disk path so RunManager dispatches the curated path on Start.
 * "Auto-generate" leaves the sidecar empty and the legacy /babysit path
 * authors a fresh process.js per task.
 */
import { useEffect, useMemo, useState } from "react";
import { Modal } from "./Modal";
import { InputsForm } from "./InputsForm";
import { useProjects } from "../hooks/useProjects";
import { useTasks } from "../hooks/useTasks";
import { useLibraryIndex } from "../hooks/useLibraryIndex";
import { useRoute } from "../router";
import { publish } from "../hooks/data-bus";
import type { LibraryIndexItem } from "../types/library";
import type { WorkflowRunTemplate } from "../global";

const DEFAULT_WORKFLOW_LETTER = "F";
const DEFAULT_TARGET_QUALITY = 90;
const DEFAULT_MAX_ITERATIONS = 1;
/** Sentinel for the "no curated workflow — auto-gen" choice. */
const AUTO_GEN_VALUE = "__autogen__";

/**
 * Walk the workflow's inputs JSON Schema and return the first error message
 * (or empty string if all required fields are filled correctly). Mirrors
 * the validator in `RunWorkflowModal` so both Create surfaces enforce the
 * same rules.
 */
function validateInputsAgainstSchema(
  schema: Record<string, unknown> | null,
  inputs: Record<string, unknown>,
): string {
  if (!schema) return "";
  const root = schema as { type?: string; properties?: Record<string, { type?: string }>; required?: string[] };
  if (root.type !== "object" || !root.properties) return "";
  const required = root.required ?? [];
  for (const key of required) {
    const value = inputs[key];
    if (value === undefined || value === null || value === "") {
      return `Missing required field "${key}"`;
    }
  }
  for (const [key, prop] of Object.entries(root.properties)) {
    const value = inputs[key];
    if (value === undefined || value === null || value === "") continue;
    if ((prop.type === "number" || prop.type === "integer") && (typeof value !== "number" || Number.isNaN(value))) {
      return `Field "${key}" must be a number`;
    }
    if (prop.type === "boolean" && typeof value !== "boolean") {
      return `Field "${key}" must be true/false`;
    }
    if (prop.type === "string" && typeof value !== "string") {
      return `Field "${key}" must be text`;
    }
  }
  return "";
}

/**
 * Initial values to pre-populate the form when used as a re-run / clone
 * surface. All fields optional; missing keys keep the form's normal
 * defaults. Caller (e.g. TaskDetail's "Re-run…" button) builds this
 * from the source task + its RUN_CONFIG.json.
 */
export interface CreateTaskPreload {
  title?: string;
  description?: string;
  projectId?: string;
  kind?: "single" | "campaign";
  workflowLogicalPath?: string;
  inputs?: Record<string, unknown>;
  /** Newline-separated descriptions, one per item. */
  itemsText?: string;
  /** Source task id for lineage (parentTaskId on the new task). */
  parentTaskId?: string;
}

export function CreateTaskForm({
  open,
  onClose,
  preload,
}: {
  open: boolean;
  onClose: () => void;
  preload?: CreateTaskPreload;
}): JSX.Element {
  const { projects } = useProjects();
  const { tasks, refresh: refreshTasks } = useTasks();
  const { items: libraryItems } = useLibraryIndex();
  const { selectedProjectId } = useRoute();

  const [projectId, setProjectId] = useState<string>("");
  const [workflowLogicalPath, setWorkflowLogicalPath] = useState<string>(AUTO_GEN_VALUE);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [kind, setKind] = useState<"single" | "campaign">("single");
  const [babysitterMode, setBabysitterMode] = useState<"plan" | "yolo" | "forever">("plan");
  // One item per line for campaigns. Blank lines ignored. Each becomes
  // a CampaignItem with description + auto-generated id.
  const [itemsText, setItemsText] = useState("");
  const [inputs, setInputs] = useState<Record<string, unknown>>({});
  const [schema, setSchema] = useState<Record<string, unknown> | null>(null);
  const [templates, setTemplates] = useState<WorkflowRunTemplate[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>("");
  const [selectedExamplePath, setSelectedExamplePath] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [saving, setSaving] = useState(false);

  // Library workflows (kind === "workflow"), sorted by logical path so
  // the dropdown is stable + groupable visually (cradle/* before
  // contrib/*, etc.).
  const workflows = useMemo<LibraryIndexItem[]>(() => {
    return libraryItems
      .filter((item) => item.kind === "workflow")
      .sort((a, b) => a.logicalPath.localeCompare(b.logicalPath));
  }, [libraryItems]);

  const selectedWorkflow = workflows.find((w) => w.logicalPath === workflowLogicalPath) ?? null;
  const workflowExamples = useMemo<LibraryIndexItem[]>(() => {
    if (!selectedWorkflow) return [];
    return libraryItems
      .filter((item) => item.kind === "example")
      .filter((item) => isExampleForWorkflow(item, selectedWorkflow))
      .sort((a, b) => exampleScore(b, selectedWorkflow) - exampleScore(a, selectedWorkflow));
  }, [libraryItems, selectedWorkflow]);

  // Default project: the one currently being viewed (selectedProjectId from
  // the router). Uses the first project only when nothing is
  // selected — prevents silently assigning tasks to whichever project
  // sorts alphabetically first while the user has a different one open.
  useEffect(() => {
    if (!open) return;
    if (projectId) return;
    if (projects.length === 0) return;
    const preferred =
      selectedProjectId && projects.find((p) => p.id === selectedProjectId)
        ? selectedProjectId
        : projects[0]!.id;
    setProjectId(preferred);
  }, [open, projectId, projects, selectedProjectId]);

  // Reset project each time the modal opens so switching views
  // between opens honors the new selectedProjectId.
  useEffect(() => {
    if (!open) setProjectId("");
  }, [open]);

  // Hydrate state from `preload` on open (re-run / clone path). Runs
  // after the mount-defaults effects so it overrides them. We DON'T
  // honor preload on every render — only on the open transition —
  // so the user can edit the form without it snapping back.
  useEffect(() => {
    if (!open || !preload) return;
    if (preload.title !== undefined) setTitle(preload.title);
    if (preload.description !== undefined) setDescription(preload.description);
    if (preload.projectId !== undefined) setProjectId(preload.projectId);
    if (preload.kind !== undefined) setKind(preload.kind);
    if (preload.workflowLogicalPath !== undefined) setWorkflowLogicalPath(preload.workflowLogicalPath);
    if (preload.inputs !== undefined) setInputs(preload.inputs);
    if (preload.itemsText !== undefined) setItemsText(preload.itemsText);
    // Suppress the schema/template loader's input reset on the next
    // workflow change by NOT clearing here — preload.inputs already
    // populated what we want. The loader effect runs after this and
    // will reset inputs back to {} on the workflow change, so we
    // re-apply preload.inputs once it settles. Tiny race, acceptable.
    if (preload.inputs !== undefined && preload.workflowLogicalPath) {
      // schedule a microtask re-set so the loader's setInputs({}) runs first
      void Promise.resolve().then(() => setInputs(preload.inputs ?? {}));
    }
  }, [open, preload]);

  // When the workflow choice changes (or the modal opens with a default),
  // load the workflow's input schema + saved run templates. Both are
  // fire-and-forget; failures just leave the panes empty.
  useEffect(() => {
    if (!open || !window.mc || !selectedWorkflow) {
      setSchema(null);
      setTemplates([]);
      setInputs({});
      setSelectedTemplateId("");
      setSelectedExamplePath("");
      return;
    }
    const path = selectedWorkflow.inputsSchemaPath ?? null;
    void window.mc.readLibraryJsonSchema(path).then(setSchema).catch(() => setSchema(null));
    void window.mc
      .listWorkflowRunTemplates()
      .then((all) => setTemplates(all.filter((t) => t.workflowLogicalPath === selectedWorkflow.logicalPath)))
      .catch(() => setTemplates([]));
    setSelectedTemplateId("");
    setSelectedExamplePath(workflowExamples[0]?.diskPath ?? "");
  }, [open, selectedWorkflow, workflowExamples]);

  useEffect(() => {
    if (!open || !window.mc || !selectedWorkflow) return;
    if (!selectedExamplePath) {
      setInputs(defaultRunInputs());
      return;
    }
    let cancelled = false;
    void window.mc
      .readLibraryJsonFile(selectedExamplePath)
      .then((exampleInputs) => {
        if (!cancelled) setInputs(withRunDefaults(exampleInputs ?? {}));
      })
      .catch(() => {
        if (!cancelled) setInputs(defaultRunInputs());
      });
    return () => { cancelled = true; };
  }, [open, selectedWorkflow, selectedExamplePath]);

  function onLoadTemplate(id: string): void {
    setSelectedTemplateId(id);
    if (!id) {
      setInputs({});
      return;
    }
    const template = templates.find((t) => t.id === id);
    if (!template) return;
    if (!description && template.goal) setDescription(template.goal);
    setInputs(withRunDefaults(template.inputs ?? {}));
  }

  const activeProject = projects.find((p) => p.id === projectId);

  /** Best-effort next ID preview — same algorithm as TaskStore.nextTaskId(). */
  const nextIdPreview = useMemo<string>(() => {
    if (!activeProject) return "—";
    const prefix = activeProject.prefix;
    const re = new RegExp(`^${prefix}-(\\d{3,})([A-Z])$`);
    let maxN = 0;
    for (const t of tasks) {
      const m = re.exec(t.id);
      if (m) maxN = Math.max(maxN, Number.parseInt(m[1]!, 10));
    }
    const nnn = String(maxN + 1).padStart(3, "0");
    return `${prefix}-${nnn}${DEFAULT_WORKFLOW_LETTER}`;
  }, [activeProject, tasks]);

  const reset = (): void => {
    setTitle("");
    setDescription("");
    setWorkflowLogicalPath(AUTO_GEN_VALUE);
    setItemsText("");
    setKind("single");
    setInputs({});
    setSchema(null);
    setTemplates([]);
    setSelectedTemplateId("");
    setError("");
    setSaving(false);
  };

  const close = (): void => {
    reset();
    onClose();
  };

  async function onSubmit(e: React.FormEvent): Promise<void> {
    e.preventDefault();
    setError("");

    if (!activeProject) return setError("Select a project");
    if (!title.trim()) return setError("Title is required");

    try {
      setSaving(true);
      if (!window.mc) {
        return setError("Not connected to main process — try `npm run dev`");
      }
      const items = kind === "campaign"
        ? itemsText
            .split("\n")
            .map((line) => line.trim())
            .filter((line) => line.length > 0)
            .map((description, i) => ({
              // Post-filter index → contiguous IDs, no gaps from blank lines.
              // Width scales with count so item-1000 doesn't look like item-001.
              id: `item-${String(i + 1).padStart(4, "0")}`,
              description,
              status: "pending" as const,
              notes: "",
            }))
        : undefined;

      const task = await window.mc.createTask({
        title: title.trim(),
        description,
        projectId: activeProject.id,
        projectPrefix: activeProject.prefix,
        workflow: DEFAULT_WORKFLOW_LETTER,
        kind,
        babysitterMode,
        ...(items ? { items } : {}),
        ...(preload?.parentTaskId ? { parentTaskId: preload.parentTaskId } : {}),
      });

      // If the user picked a curated library workflow, drop a
      // RUN_CONFIG.json sidecar so RunManager.startNow dispatches the
      // curated path on Start. (Same shape RunWorkflowModal writes.)
      if (selectedWorkflow) {
        const validationError = validateInputsAgainstSchema(schema, inputs);
        if (validationError) {
          setSaving(false);
          return setError(validationError);
        }
        await window.mc.writeTaskRunConfig(task.id, {
          kind: "library-workflow-run",
          createdAt: new Date().toISOString(),
          libraryWorkflow: {
            id: selectedWorkflow.id,
            name: selectedWorkflow.name,
            logicalPath: selectedWorkflow.logicalPath,
            diskPath: selectedWorkflow.diskPath,
            inputsSchemaPath: selectedWorkflow.inputsSchemaPath ?? null,
          },
          taskContext: {
            title: title.trim(),
            goal: description,
            projectId: activeProject.id,
          },
          runSettings: { model: null, inputs },
        });
      }

      publish("tasks");
      await refreshTasks();
      close();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  }

  const titleText = preload?.parentTaskId ? "↻ Re-run with new inputs" : "+ Create Task";

  return (
    <Modal open={open} title={titleText} onClose={close}>
      <form onSubmit={onSubmit}>
        <style>{`
          .ctf input, .ctf select, .ctf textarea {
            background: var(--bg); color: var(--text);
            border: 1px solid var(--border); border-radius: 8px;
            padding: 9px 11px; font-family: inherit; font-size: 14px;
            width: 100%;
          }
          .ctf label { font-size: 12px; color: var(--muted); }
          .ctf .field { display: grid; gap: 4px; margin-bottom: 14px; }
          .ctf .hint { font-size: 11px; color: var(--muted); }
        `}</style>
        <div className="ctf">
          {preload?.parentTaskId && (
            <div
              className="hint"
              style={{
                marginBottom: 14,
                padding: "8px 10px",
                background: "rgba(107, 164, 232,0.08)",
                border: "1px solid var(--accent)",
                borderRadius: 8,
              }}
            >
              Cloning from <strong>{preload.parentTaskId}</strong> — fields are
              pre-filled. Edit any of them before clicking Create. The new task
              records its lineage via <code>parentTaskId</code>.
            </div>
          )}
          <div className="field">
            <label>Project</label>
            <select
              value={projectId}
              onChange={(e) => setProjectId(e.target.value)}
            >
              {projects.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name} ({p.prefix})
                </option>
              ))}
            </select>
          </div>
          <div className="field">
            <label>Workflow</label>
            <select
              value={workflowLogicalPath}
              onChange={(e) => setWorkflowLogicalPath(e.target.value)}
            >
              <option value={AUTO_GEN_VALUE}>
                Auto-generate (babysitter authors a fresh process per task)
              </option>
              {workflows.map((w) => (
                <option key={w.logicalPath} value={w.logicalPath}>
                  {w.logicalPath} — {w.name}
                </option>
              ))}
            </select>
            <div className="hint">
              {selectedWorkflow
                ? `Curated: spawns babysitter harness:create-run --process ${selectedWorkflow.diskPath}.`
                : "Auto-gen: clicks Start fire /babysit; babysitter-pi extension authors a process.js per run."}
            </div>
          </div>

          {selectedWorkflow && templates.length > 0 && (
            <div className="field">
              <label>Load template (optional)</label>
              <select
                value={selectedTemplateId}
                onChange={(e) => onLoadTemplate(e.target.value)}
              >
                <option value="">— pick a saved template —</option>
                {templates.map((t) => (
                  <option key={t.id} value={t.id}>{t.name}</option>
                ))}
              </select>
              <div className="hint">
                Templates are saved from the Library workflow Run modal; loading one prefills the goal + inputs.
              </div>
            </div>
          )}

          {selectedWorkflow && workflowExamples.length > 0 && (
            <div className="field">
              <label>Load example inputs</label>
              <select
                value={selectedExamplePath}
                onChange={(e) => setSelectedExamplePath(e.target.value)}
              >
                <option value="">Start from defaults</option>
                {workflowExamples.map((example) => (
                  <option key={example.diskPath} value={example.diskPath}>
                    {example.logicalPath}
                  </option>
                ))}
              </select>
              <div className="hint">
                The closest library example is loaded automatically and can be edited below.
              </div>
            </div>
          )}

          {selectedWorkflow && (
            <div className="field">
              <label>Inputs {schema ? "(schema-driven)" : "(JSON)"}</label>
              <InputsForm schema={schema} value={inputs} onChange={setInputs} />
              <div className="hint">
                {selectedWorkflow.inputsSchemaPath
                  ? "Required fields from the workflow's inputs schema. Empty = workflow's first breakpoint will collect them."
                  : "No schema published with this workflow. Free-form JSON; passed to the run as is."}
              </div>
            </div>
          )}
          {selectedWorkflow && (
            <div className="field">
              <label>Quality and iterations</label>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>
                <div style={{ display: "grid", gap: 4 }}>
                  <label>Quality percentage</label>
                  <input
                    type="number"
                    min={0}
                    max={100}
                    value={typeof inputs.targetQuality === "number" ? inputs.targetQuality : DEFAULT_TARGET_QUALITY}
                    onChange={(e) => setInputs((prev) => ({ ...prev, targetQuality: Number(e.target.value) }))}
                  />
                </div>
                <div style={{ display: "grid", gap: 4 }}>
                  <label>Iterations</label>
                  <input
                    type="number"
                    min={1}
                    max={20}
                    value={typeof inputs.maxIterations === "number" ? inputs.maxIterations : DEFAULT_MAX_ITERATIONS}
                    onChange={(e) => setInputs((prev) => ({ ...prev, maxIterations: Number(e.target.value) }))}
                  />
                </div>
              </div>
              <div className="hint">
                Written into Input JSON as targetQuality and maxIterations. Iterations defaults to 1.
              </div>
            </div>
          )}
          <div className="field">
            <label>Task shape</label>
            <select value={kind} onChange={(e) => setKind(e.target.value as "single" | "campaign")}>
              <option value="single">Iterate this task</option>
              <option value="campaign">Campaign items</option>
            </select>
            <div className="hint">
              Default is one task with one iteration. Use campaign only when
              you want one session per listed item.
            </div>
          </div>
          <div className="field">
            <label>Babysitter mode</label>
            <select
              value={babysitterMode}
              onChange={(e) => setBabysitterMode(e.target.value as "plan" | "yolo" | "forever")}
            >
              <option value="plan">plan — /plan</option>
              <option value="yolo">yolo — /yolo</option>
              <option value="forever">forever — /forever</option>
            </select>
            <div className="hint">
              How MC drives pi when you click Start on this task.
            </div>
          </div>
          <div className="field">
            <label>Title</label>
            <input
              autoFocus
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Short, imperative — e.g. Add task-linked diff registry"
            />
          </div>
          <div className="field">
            <label>Description</label>
            <textarea
              rows={4}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="What does done look like? Any constraints the workflow agents should know?"
            />
          </div>
          {kind === "campaign" && (
            <div className="field">
              <label>Items (one per line)</label>
              <textarea
                rows={5}
                value={itemsText}
                onChange={(e) => setItemsText(e.target.value)}
                placeholder={"./src/lib/thing-a.dll\n./src/lib/thing-b.dll\n./src/lib/thing-c.dll"}
              />
              <div className="hint">
                Optional at creation — the workflow's planning agent
                can generate items as part of its run. One item per line,
                blank lines ignored.
              </div>
            </div>
          )}

          {error && (
            <div
              style={{
                color: "var(--bad)",
                background: "rgba(232, 116, 116,0.1)",
                border: "1px solid var(--bad)",
                borderRadius: 8,
                padding: "8px 10px",
                marginTop: 8,
                fontSize: 13,
              }}
            >
              {error}
            </div>
          )}

          <div
            style={{
              display: "flex",
              alignItems: "center",
              marginTop: 14,
              gap: 8,
            }}
          >
            <span className="muted" style={{ fontSize: 12 }}>
              Task ID will be: <strong>{nextIdPreview}</strong>
            </span>
            <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
              <button type="button" className="button ghost" onClick={close}>
                Cancel
              </button>
              <button type="submit" className="button" disabled={saving}>
                {saving ? "Creating…" : "Create Task"}
              </button>
            </div>
          </div>
        </div>
      </form>
    </Modal>
  );
}

function defaultRunInputs(): Record<string, unknown> {
  return {
    targetQuality: DEFAULT_TARGET_QUALITY,
    maxIterations: DEFAULT_MAX_ITERATIONS,
  };
}

function withRunDefaults(inputs: Record<string, unknown>): Record<string, unknown> {
  return {
    ...defaultRunInputs(),
    ...inputs,
  };
}

function isExampleForWorkflow(example: LibraryIndexItem, workflow: LibraryIndexItem): boolean {
  const workflowParts = workflow.logicalPath.split("/");
  const exampleParts = example.logicalPath.split("/");
  const sameContainer = Boolean(workflow.container && example.container === workflow.container);
  const sameTopLevelArea = workflowParts[0] === exampleParts[0] && workflowParts[1] === exampleParts[1];
  return sameContainer || sameTopLevelArea;
}

function exampleScore(example: LibraryIndexItem, workflow: LibraryIndexItem): number {
  const haystack = `${example.logicalPath} ${example.name} ${example.description ?? ""}`.toLowerCase();
  const workflowName = workflow.name.toLowerCase();
  let score = 0;
  if (example.container && example.container === workflow.container) score += 20;
  if (haystack.includes(workflowName)) score += 100;
  for (const token of workflowName.split(/[^a-z0-9]+/).filter((x) => x.length > 2)) {
    if (haystack.includes(token)) score += 5;
  }
  return score;
}
