/**
 * Create Task form — pick project + workflow, enter title + description.
 *
 * Task ID is auto-generated by the store based on the project's prefix and
 * the workflow letter (e.g. DA-017F). We preview the NEXT id by fetching
 * the current task list and finding the max number for this prefix.
 */
import { useEffect, useMemo, useState } from "react";
import { Modal } from "./Modal";
import { useProjects } from "../hooks/useProjects";
import { useWorkflows } from "../hooks/useWorkflows";
import { useTasks } from "../hooks/useTasks";
import { publish } from "../hooks/data-bus";

export function CreateTaskForm({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}): JSX.Element {
  const { projects } = useProjects();
  const { workflows } = useWorkflows();
  const { tasks, refresh: refreshTasks } = useTasks();

  const [projectId, setProjectId] = useState<string>("");
  const [workflow, setWorkflow] = useState<string>("F");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [error, setError] = useState<string>("");
  const [saving, setSaving] = useState(false);

  // Default project on first open
  useEffect(() => {
    if (open && !projectId && projects.length > 0) {
      setProjectId(projects[0]!.id);
    }
  }, [open, projectId, projects]);

  const activeProject = projects.find((p) => p.id === projectId);

  /** Best-effort next ID preview — same algorithm as TaskStore.nextTaskId(). */
  const nextIdPreview = useMemo<string>(() => {
    if (!activeProject) return "—";
    const prefix = activeProject.prefix;
    const re = new RegExp(`^${prefix}-(\\d{3,})([A-Z])$`);
    let maxN = 0;
    for (const t of tasks) {
      const m = re.exec(t.id);
      if (m) maxN = Math.max(maxN, Number.parseInt(m[1]!, 10));
    }
    const nnn = String(maxN + 1).padStart(3, "0");
    return `${prefix}-${nnn}${workflow}`;
  }, [activeProject, tasks, workflow]);

  const reset = (): void => {
    setTitle("");
    setDescription("");
    setError("");
    setSaving(false);
  };

  const close = (): void => {
    reset();
    onClose();
  };

  async function onSubmit(e: React.FormEvent): Promise<void> {
    e.preventDefault();
    setError("");

    if (!activeProject) return setError("Select a project");
    if (!title.trim()) return setError("Title is required");

    try {
      setSaving(true);
      if (!window.mc) {
        return setError("Not connected to main process — try `npm run dev`");
      }
      await window.mc.createTask({
        title: title.trim(),
        description,
        projectId: activeProject.id,
        projectPrefix: activeProject.prefix,
        workflow,
      });
      publish("tasks");
      await refreshTasks();
      close();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal open={open} title="+ Create Task" onClose={close}>
      <form onSubmit={onSubmit}>
        <style>{`
          .ctf input, .ctf select, .ctf textarea {
            background: var(--bg); color: var(--text);
            border: 1px solid var(--border); border-radius: 8px;
            padding: 9px 11px; font-family: inherit; font-size: 14px;
            width: 100%;
          }
          .ctf label { font-size: 12px; color: var(--muted); }
          .ctf .field { display: grid; gap: 4px; margin-bottom: 14px; }
          .ctf .hint { font-size: 11px; color: var(--muted); }
        `}</style>
        <div className="ctf">
          <div className="field">
            <label>Project</label>
            <select
              value={projectId}
              onChange={(e) => setProjectId(e.target.value)}
            >
              {projects.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name} ({p.prefix})
                </option>
              ))}
            </select>
          </div>
          <div className="field">
            <label>Workflow</label>
            <select
              value={workflow}
              onChange={(e) => setWorkflow(e.target.value)}
            >
              {workflows.map((w) => (
                <option key={w.code} value={w.code}>
                  {w.code} · {w.name} — {w.description || "(no description)"}
                </option>
              ))}
            </select>
            <div className="hint">Read from the <code>workflows/</code> folder at boot.</div>
          </div>
          <div className="field">
            <label>Title</label>
            <input
              autoFocus
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Short, imperative — e.g. Add task-linked diff registry"
            />
          </div>
          <div className="field">
            <label>Description</label>
            <textarea
              rows={4}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="What does done look like? Any constraints the Planner should know?"
            />
          </div>

          {error && (
            <div
              style={{
                color: "var(--bad)",
                background: "rgba(255,123,123,0.1)",
                border: "1px solid var(--bad)",
                borderRadius: 8,
                padding: "8px 10px",
                marginTop: 8,
                fontSize: 13,
              }}
            >
              {error}
            </div>
          )}

          <div
            style={{
              display: "flex",
              alignItems: "center",
              marginTop: 14,
              gap: 8,
            }}
          >
            <span className="muted" style={{ fontSize: 12 }}>
              Task ID will be: <strong>{nextIdPreview}</strong>
            </span>
            <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
              <button type="button" className="button ghost" onClick={close}>
                Cancel
              </button>
              <button type="submit" className="button" disabled={saving}>
                {saving ? "Creating…" : "Create Task"}
              </button>
            </div>
          </div>
        </div>
      </form>
    </Modal>
  );
}
