/**
 * Create Task form — pick project + workflow, enter title + description.
 *
 * Task ID is auto-generated by the store based on the project's prefix and
 * a fixed workflow letter (e.g. DA-017F). The optional workflow picker
 * sources from `library/_index.json` (kind:"workflow"); when one's
 * selected, on submit we write a `RUN_CONFIG.json` sidecar with the
 * chosen disk path so RunManager dispatches the curated path on Start.
 * "Auto-generate" leaves the sidecar empty and the legacy /babysit path
 * authors a fresh process.js per task.
 */
import { useEffect, useMemo, useState } from "react";
import { Modal } from "./Modal";
import { useProjects } from "../hooks/useProjects";
import { useTasks } from "../hooks/useTasks";
import { useLibraryIndex } from "../hooks/useLibraryIndex";
import { useRoute } from "../router";
import { publish } from "../hooks/data-bus";
import type { LibraryIndexItem } from "../types/library";

const DEFAULT_WORKFLOW_LETTER = "F";
/** Sentinel for the "no curated workflow — auto-gen" choice. */
const AUTO_GEN_VALUE = "__autogen__";

export function CreateTaskForm({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}): JSX.Element {
  const { projects } = useProjects();
  const { tasks, refresh: refreshTasks } = useTasks();
  const { items: libraryItems } = useLibraryIndex();
  const { selectedProjectId } = useRoute();

  const [projectId, setProjectId] = useState<string>("");
  const [workflowLogicalPath, setWorkflowLogicalPath] = useState<string>(AUTO_GEN_VALUE);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [kind, setKind] = useState<"single" | "campaign">("single");
  // One item per line for campaigns. Blank lines ignored. Each becomes
  // a CampaignItem with description + auto-generated id.
  const [itemsText, setItemsText] = useState("");
  const [error, setError] = useState<string>("");
  const [saving, setSaving] = useState(false);

  // Library workflows (kind === "workflow"), sorted by logical path so
  // the dropdown is stable + groupable visually (cradle/* before
  // contrib/*, etc.).
  const workflows = useMemo<LibraryIndexItem[]>(() => {
    return libraryItems
      .filter((item) => item.kind === "workflow")
      .sort((a, b) => a.logicalPath.localeCompare(b.logicalPath));
  }, [libraryItems]);

  const selectedWorkflow = workflows.find((w) => w.logicalPath === workflowLogicalPath) ?? null;

  // Default project: the one currently being viewed (selectedProjectId from
  // the router). Uses the first project only when nothing is
  // selected — prevents silently assigning tasks to whichever project
  // sorts alphabetically first while the user has a different one open.
  useEffect(() => {
    if (!open) return;
    if (projectId) return;
    if (projects.length === 0) return;
    const preferred =
      selectedProjectId && projects.find((p) => p.id === selectedProjectId)
        ? selectedProjectId
        : projects[0]!.id;
    setProjectId(preferred);
  }, [open, projectId, projects, selectedProjectId]);

  // Reset project each time the modal opens so switching views
  // between opens honors the new selectedProjectId.
  useEffect(() => {
    if (!open) setProjectId("");
  }, [open]);

  const activeProject = projects.find((p) => p.id === projectId);

  /** Best-effort next ID preview — same algorithm as TaskStore.nextTaskId(). */
  const nextIdPreview = useMemo<string>(() => {
    if (!activeProject) return "—";
    const prefix = activeProject.prefix;
    const re = new RegExp(`^${prefix}-(\\d{3,})([A-Z])$`);
    let maxN = 0;
    for (const t of tasks) {
      const m = re.exec(t.id);
      if (m) maxN = Math.max(maxN, Number.parseInt(m[1]!, 10));
    }
    const nnn = String(maxN + 1).padStart(3, "0");
    return `${prefix}-${nnn}${DEFAULT_WORKFLOW_LETTER}`;
  }, [activeProject, tasks]);

  const reset = (): void => {
    setTitle("");
    setDescription("");
    setWorkflowLogicalPath(AUTO_GEN_VALUE);
    setItemsText("");
    setKind("single");
    setError("");
    setSaving(false);
  };

  const close = (): void => {
    reset();
    onClose();
  };

  async function onSubmit(e: React.FormEvent): Promise<void> {
    e.preventDefault();
    setError("");

    if (!activeProject) return setError("Select a project");
    if (!title.trim()) return setError("Title is required");

    try {
      setSaving(true);
      if (!window.mc) {
        return setError("Not connected to main process — try `npm run dev`");
      }
      const items = kind === "campaign"
        ? itemsText
            .split("\n")
            .map((line) => line.trim())
            .filter((line) => line.length > 0)
            .map((description, i) => ({
              // Post-filter index → contiguous IDs, no gaps from blank lines.
              // Width scales with count so item-1000 doesn't look like item-001.
              id: `item-${String(i + 1).padStart(4, "0")}`,
              description,
              status: "pending" as const,
              notes: "",
            }))
        : undefined;

      const task = await window.mc.createTask({
        title: title.trim(),
        description,
        projectId: activeProject.id,
        projectPrefix: activeProject.prefix,
        workflow: DEFAULT_WORKFLOW_LETTER,
        kind,
        ...(items ? { items } : {}),
      });

      // If the user picked a curated library workflow, drop a
      // RUN_CONFIG.json sidecar so RunManager.startNow dispatches the
      // curated path on Start. (Same shape RunWorkflowModal writes.)
      if (selectedWorkflow) {
        await window.mc.writeTaskRunConfig(task.id, {
          kind: "library-workflow-run",
          createdAt: new Date().toISOString(),
          libraryWorkflow: {
            id: selectedWorkflow.id,
            name: selectedWorkflow.name,
            logicalPath: selectedWorkflow.logicalPath,
            diskPath: selectedWorkflow.diskPath,
            inputsSchemaPath: selectedWorkflow.inputsSchemaPath ?? null,
          },
          taskContext: {
            title: title.trim(),
            goal: description,
            projectId: activeProject.id,
          },
          runSettings: { model: null, inputs: {} },
        });
      }

      publish("tasks");
      await refreshTasks();
      close();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal open={open} title="+ Create Task" onClose={close}>
      <form onSubmit={onSubmit}>
        <style>{`
          .ctf input, .ctf select, .ctf textarea {
            background: var(--bg); color: var(--text);
            border: 1px solid var(--border); border-radius: 8px;
            padding: 9px 11px; font-family: inherit; font-size: 14px;
            width: 100%;
          }
          .ctf label { font-size: 12px; color: var(--muted); }
          .ctf .field { display: grid; gap: 4px; margin-bottom: 14px; }
          .ctf .hint { font-size: 11px; color: var(--muted); }
        `}</style>
        <div className="ctf">
          <div className="field">
            <label>Project</label>
            <select
              value={projectId}
              onChange={(e) => setProjectId(e.target.value)}
            >
              {projects.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name} ({p.prefix})
                </option>
              ))}
            </select>
          </div>
          <div className="field">
            <label>Workflow</label>
            <select
              value={workflowLogicalPath}
              onChange={(e) => setWorkflowLogicalPath(e.target.value)}
            >
              <option value={AUTO_GEN_VALUE}>
                Auto-generate (babysitter authors a fresh process per task)
              </option>
              {workflows.map((w) => (
                <option key={w.logicalPath} value={w.logicalPath}>
                  {w.logicalPath} — {w.name}
                </option>
              ))}
            </select>
            <div className="hint">
              {selectedWorkflow
                ? `Curated: spawns babysitter harness:create-run --process ${selectedWorkflow.diskPath}.`
                : "Auto-gen: clicks Start fire /babysit; babysitter-pi extension authors a process.js per run."}
            </div>
          </div>
          <div className="field">
            <label>Kind</label>
            <select value={kind} onChange={(e) => setKind(e.target.value as "single" | "campaign")}>
              <option value="single">Single — one task × N cycles</option>
              <option value="campaign">Campaign — one task × N items (iterate each)</option>
            </select>
            <div className="hint">
              Campaigns process a list of items, one session per item. Runtime
              iteration is not wired yet — items show up for planning only.
            </div>
          </div>
          <div className="field">
            <label>Title</label>
            <input
              autoFocus
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Short, imperative — e.g. Add task-linked diff registry"
            />
          </div>
          <div className="field">
            <label>Description</label>
            <textarea
              rows={4}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="What does done look like? Any constraints the Planner should know?"
            />
          </div>
          {kind === "campaign" && (
            <div className="field">
              <label>Items (one per line)</label>
              <textarea
                rows={5}
                value={itemsText}
                onChange={(e) => setItemsText(e.target.value)}
                placeholder={"./src/lib/thing-a.dll\n./src/lib/thing-b.dll\n./src/lib/thing-c.dll"}
              />
              <div className="hint">
                Optional at creation — Planner can generate items as part of
                its run. One item per line, blank lines ignored.
              </div>
            </div>
          )}

          {error && (
            <div
              style={{
                color: "var(--bad)",
                background: "rgba(255,123,123,0.1)",
                border: "1px solid var(--bad)",
                borderRadius: 8,
                padding: "8px 10px",
                marginTop: 8,
                fontSize: 13,
              }}
            >
              {error}
            </div>
          )}

          <div
            style={{
              display: "flex",
              alignItems: "center",
              marginTop: 14,
              gap: 8,
            }}
          >
            <span className="muted" style={{ fontSize: 12 }}>
              Task ID will be: <strong>{nextIdPreview}</strong>
            </span>
            <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
              <button type="button" className="button ghost" onClick={close}>
                Cancel
              </button>
              <button type="submit" className="button" disabled={saving}>
                {saving ? "Creating…" : "Create Task"}
              </button>
            </div>
          </div>
        </div>
      </form>
    </Modal>
  );
}
