import { promises as fs } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

export type WorkflowInputWrapperOptions = {
  taskDir: string;
  workflowPath: string;
  inputs?: Record<string, unknown>;
};

/**
 * Creates a per-run workflow wrapper that injects MissionControl run inputs
 * into the Babysitter process inputs object.
 *
 * This keeps Babysitter as the orchestration engine while ensuring values
 * collected/stored by MissionControl are actually visible to
 * `process(inputs, ctx)`.
 */
export async function createWorkflowInputWrapper(
  options: WorkflowInputWrapperOptions,
): Promise<string> {
  const wrapperDir = path.join(options.taskDir, ".mc", "generated");
  await fs.mkdir(wrapperDir, { recursive: true });

  const wrapperPath = path.join(wrapperDir, "workflow-input-wrapper.js");
  const workflowUrl = pathToFileURL(options.workflowPath).href;
  const inputsJson = JSON.stringify(options.inputs ?? {}, null, 2);

  const source = `// Generated by MissionControl. Do not edit.\n` +
    `// Wraps a library workflow so MC run inputs reach Babysitter process(inputs, ctx).\n\n` +
    `import { process as realProcess } from ${JSON.stringify(workflowUrl)};\n\n` +
    `const mcInputs = ${inputsJson};\n\n` +
    `export async function process(inputs = {}, ctx) {\n` +
    `  return realProcess({ ...mcInputs, ...inputs }, ctx);\n` +
    `}\n`;

  await fs.writeFile(wrapperPath, source, "utf8");
  return wrapperPath;
}
